### ISSUE TITLE
Bug exporting grades

### ISSUE THREAD

**Issue by rcg0** [jfisteus/eyegrade#124]
When exporting grades listing, fields "Student last name" and "Student first name" are exported as blank (the columns are created, but empty)

System information: Ubuntu 16.04 LTS

**Comment by jfisteus** [comment]
Thanks for your report.

After having examined the session database you also passed me to reproduce the issue, I've seen that the problem is that student names were imported as a single column with format "Simpson, Bart". Eyegrade has no support for trying to extract first and last name when imported in a single column. There are many languages and cultures with different ways of expressing names, and supporting that would be challenging and probably not worth it.

Support for separate first/last name is provided when you import them in two separate columns. See https://www.eyegrade.org/doc/user-manual/#student-list-files
