### ISSUE TITLE
ERROR: No matching distribution found for black

### ISSUE THREAD

**Issue by ginterez** [jfisteus/eyegrade#139]
I get this error when I try to install the requirements-dev.txt

  ERROR: Could not find a version that satisfies the requirement black (from -r requirements-dev.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for black (from -r requirements-dev.txt (line 2))

I'm currently using python 3.5.2

**Comment by jfisteus** [comment]
I use *black* to automatically apply the same code formatting conventions across all the sources of the project. You are unable to install it because it requires python 3.6.0 or a later version:

https://pypi.org/project/black/

Nevertheless, *black* isn't necessary to run Eyegrade or to modify its sources, so you can skip its installation and continue using Python 3.5 if you want. In case you modify anything and want to contribute it back to the project, I can run *black* on your contributions if needed.
