### ISSUE TITLE
How to run for development?

### ISSUE THREAD

**Issue by jiharaguiapal** [jfisteus/eyegrade#140]
I'm still new with python and I'm trying to run eyegrade for development. Is there anyone who could list all the steps and all I need to download to run eyegrade for development?

**Comment by jfisteus** [comment]
You'll need Python 3.6 or a later version (it's also possible to use 3.5, but in that case you won't be able to run the *black* code formatter). You should also have *git* installed to clone Eyegrade sources from its GitHub repository, commit your changes, etc.:  https://git-scm.com/

The first step is cloning Eyegrade's repository. From the command line run:

```
git clone https://github.com/jfisteus/eyegrade.git
cd eyegrade
```

From now on, I assume your terminal is places in Eyegrade's main directory, the one that was created by *git* in the previous command. Now, you have to install Eyegrade's requirements. I strongly recommend installing them on a virtual environment:

```
python -m venv venv
```

The previous command creates a new directory within Eyegrade's main directory with an isolated python environment. Every time you open a new command line terminal to work on the project, you need to activate it:

```
# On Linux:
source venv/bin/activate

# On Windows:
venv\Scripts\activate.bat
```

Now, with your virtual enviroment activated, install Eyegrade's dependencies (listed in `requirements.txt`):

```
pip install -r requirements.txt
```

You can also install *black* and run it on the files you modify so that your code is re-formatted according to *black*'s coding conventions, which are used in the rest of Eyegarde's soruces:

```
pip install black

# Example of applying black to all the sources:
black eyegrade/*.py eyegrade/*/*.py
```

Finally, you can run Eyegrade with:

```
python -m eyegrade
```

Please, let me know if you get it to work or need further help.

**Comment by ginterez** [comment]
When I try to apply black to all the sources I got this error

(venv) C:\Users\User\Desktop\eyegrade>black eyegrade/*.py eyegrade/*/*.py
Usage: black [OPTIONS] [SRC]...
Try "black -h" for help.
Error: Invalid value for "[SRC]...": Path "eyegrade/*.py" does not exist.

**Comment by jfisteus** [comment]
My fault. I've written the Unix version of the command because it's what I use. In Windows just run:

```
black eyegrade\*.py eyegrade\*\*.py
```

from Eyegrade's main folder.

**Comment by ginterez** [comment]
I still got the same error

**Comment by jfisteus** [comment]
It should work. Make sure you type everything, including the asterisks. If it fails, post the error message here, please.

Anyway, as I commented on the answer to another issue, black is only used to unify coding style in the sources. You can run and make changes to Eyegrade without running black.
