### ISSUE TITLE
Can't load a TSV students list, if the students full name has a coma

### ISSUE THREAD

**Issue by dracometallium** [jfisteus/eyegrade#160]
Hello, I have found that if I try to load an students list stored as a `TSV` (tab separated values) where the students full name has a coma, eyegrade does not recognize the format. It show an error that reads: "the syntax of the student list isn't correct".

If the first line does not have a coma (like in the case it has a header), it does recognize the format correctly.

I attach both cases.
[examples.zip](https://github.com/jfisteus/eyegrade/files/8654356/examples.zip)

**Comment by jfisteus** [comment]
Thanks for reporting this issue. I'll take a look at it as soon as I can.

**Comment by jfisteus** [comment]
Thanks again for reporting the issue. The csv.Sniffer module was guessing the separator was a comma instead of a tab. I've made Eyegrade treat the file as TSV when at least one tabulator is seen at the beginning of the file.

The fix will appear at the next release of Eyegrade, but the relase won't happen until other features I've planned for it are ready.

**Comment by dracometallium** [comment]
Thanks!
